server:
  port: 7002
spring:
  application:
    name: user-app

  datasource:
    url: jdbc:postgresql://localhost:5433/USER_DEV
    username: userDevUser
    password: Dev_PaSSw0rd
    hikari:
      maximum-pool-size: 5
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: false
    database: POSTGRESQL
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        enable_lazy_load_no_trans: true
        temp:
          use_jdbc_metadata_defaults: false
  liquibase:
    change-log: db/changelog/db.changelog-master.xml
    drop-first: true

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
